// 1. Swap react-router-dom for next/router
import { useRouter } from "next/router";
import React, { useState } from "react";
import { useSWRConfig } from "swr/_internal";

// PENDING
import { BASE_INVENTORY_URL } from "@/components/ui/backend/organization_call_backend";
// import { createItem } from '../hooks/organization_call_backend';
import {
  createMemberClean,
  updateMemberClean,
} from "@/components/ui/backend/organization_clean_backend_calls";
import { Member_Details_Interface } from "@/components/ui/card_organization_member_details_modal";
import Header from "@/components/ui/navbar_organization";

const Organization_Add_Member = () => {
  // get the query from the other buttons
  const { mode, data } = useRouter().query;

  // covnert the data back from json
  const parsedData: Member_Details_Interface | null = data
    ? JSON.parse(data as string)
    : null;

  // it creates a page stack that we can use to navigate
  // when to use and should we replace all href with router.push?
  // we only use this when we want to have buttons that go back to certain pages or after finishing a task
  // we use Link href when we want to move to static pages
  const router = useRouter();

  // this is the form data management state
  // so that meaans itsl like a clipboard, at the start its empty, but when the user writes, it updates
  // we use partial so that we dont ahve to include each field at the start
  const [formData, setFormData] = useState<Partial<Member_Details_Interface>>({
    // id is excluded because it will be auto generated by backend
    // id: number,
    name: mode === "add" ? "" : parsedData?.name,
    email: mode === "add" ? "" : parsedData?.email,
    phoneNumber: mode === "add" ? "" : parsedData?.phoneNumber,
    notes: mode === "add" ? "" : parsedData?.notes,

    // organization is kept away because we will fix it to the name of the organization that is logged in
    // organization: "",

    // joinedOn is kept away because we will fix it to the current date
    // joinedOn: "",

    // isStillHere is kept away because we will fix it to true
    // isStillHere: "",

    // itemsBorrowed is kept away because we will fix it to 0
    // itemsBorrowed: "",

    // lastBorrowedOn is kept away because we will fix it to the current date
    // lastBorrowedOn: "",

    // totalFriends is kept away because we will fix it to 0
    // totalFriends: "",

    // friends is kept away because we will fix it to an empty array
    // friends: "",

    // totalClubs is kept away because we will fix it to 0
    // totalClubs: "",

    // clubs is kept away because we will fix it to an empty array
    // clubs: "",
  });

  // used whenever you type in the form fields
  // e is event, and we get the name and value from the target of the event
  const handleChange = (
    // so only handle changes in input or textarea elements
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>,
  ) => {
    // name is the name of the element like details field
    // value is the input
    const { name, value } = e.target;

    // it copies the exisiting form data and updates the field that changed\
    // use brackets to use a variable as the key name
    // if no brackets, it would just update the name field
    setFormData({ ...formData, [name]: value });
  };

  // this is to get the refresh function from SWR
  const { mutate } = useSWRConfig(); // 1. Initiate at the TOP

  const handleSave = async (e: React.FormEvent) => {
    // this is to prevent the page from emptying all the fields and refreshing
    e.preventDefault();

    try {
      if (mode === "add" && parsedData) {
        // 2. Call the action (The "Messenger")
        await createMemberClean({ ...formData } as Member_Details_Interface);

        // 3. Tell SWR to refresh the Dashboard data
        // This tells SWR: "The data at BASE_INVENTORY_URL is old, please go get the new list!"
        mutate([`${BASE_INVENTORY_URL}`, "all"]);

        alert("Member created!");
      } else {
        // 2. Call the action (The "Messenger")
        await updateMemberClean(formData);

        // 3. Tell SWR to refresh the Dashboard data
        // This tells SWR: "The data at BASE_INVENTORY_URL is old, please go get the new list!"
        mutate([`${BASE_INVENTORY_URL}`, "all"]);

        alert("Member updated!");
      }

      // go back to dashboard
      // router.push('/organization_dashboard');
      router.back();
    } catch (error) {
      alert("Failed to save member: " + error);
    }
  };

  return (
    <main>
      <Header />
      <div className="form-container">
        <h2 className="form-title">
          {" "}
          {mode === "add" ? "Add new" : "Edit"} Member
        </h2>

        <form onSubmit={handleSave}>
          <div className="form-group">
            <label className="form-label">Member Name</label>
            <input
              className="form-input"
              name="name"
              value={formData.name}
              onChange={handleChange}
              required
            />
          </div>

          <div className="form-group">
            <label className="form-label">Email</label>
            <input
              className="form-input"
              name="email"
              value={formData.email}
              onChange={handleChange}
              required
            />
          </div>

          <div className="form-group">
            <label className="form-label">Phone Number</label>
            <input
              className="form-input"
              name="phoneNumber"
              value={formData.phoneNumber}
              onChange={handleChange}
              required
            />
          </div>

          <div className="form-group">
            <label className="form-label">Notes</label>
            <textarea
              className="form-textarea"
              name="notes"
              value={formData.notes}
              onChange={handleChange}
            />
          </div>

          <div className="button-group">
            <button type="submit" className="btn-save">
              Save
            </button>

            {/* 4. Use router.back() for the cancel button */}
            <button
              type="button"
              className="btn-cancel"
              onClick={() => router.back()}
            >
              Cancel
            </button>
          </div>
        </form>
      </div>
    </main>
  );
};

export default Organization_Add_Member;

/*
Notes on why useSWR dosent work 
1. can only be invoked on the top level of the component, 
  1.1 so why our code can use useSWR in the backend calls in getAllItemsClean but cannot in the post?
    1.1.1 that is because getAllItemsClean is invoked at the page level, so its top level
    1.1.2 but createNewItemClean is invoked inside a button, so its not top level
2. useSWR is like a camera, it watches a URL, using it to save is wrong 

so what did we do instead?
1. change the call to a direct async
2. perform a manual refresh 

what is uswSWRConfig and mutate?\
- SWR is a warehouse
- useSWR is like a  worker workign in  a specific aisle (URL)
- useSWRConfig is like the warehouse manager, it has access to all aisles (all URLs)
- so when we call the mutate allows u to walk to anyw aisle and do something

*/
