# Generated by Django 5.2.8 on 2026-01-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='borrowerName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='collectionPoint',
            field=models.CharField(default='Demo Collection Point', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='organization',
            field=models.CharField(default='Demo Organization', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='returnedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
