# Generated by Django 5.2.8 on 2026-01-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_availability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='borrowed_on',
            new_name='borrowedOn',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='due_on',
            new_name='dueOn',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='expiry_date',
            new_name='expiryDate',
        ),
    ]
