# Generated by Django 5.2.8 on 2026-01-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_borrowed_on_inventoryitem_borrowedon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='date_added',
            new_name='dateAdded',
        ),
    ]
